export const translations = {
  en: {
    lang: 'en', pageTitle: 'RIGHT ADS — Make your brand impossible to miss',
    announcement: ['DESIGN · PRINT · INSTALL', 'BUILT TO BE SEEN'],
    nav: ['What we make', 'How it works', 'Image library'], headerCall: 'Talk to a human', menu: 'Open menu',
    hero: { eyebrow: '01 / FULL-SERVICE PRINT STUDIO', eyebrowEnd: 'EST. FOR IMPACT', title: 'Your vision.<br><span class="headline-accent">Out in the world.</span>', lede: 'From first sketch to final install, we make physical brand experiences impossible to miss.', compat: 'RESPONSIVE DESIGN · ANDROID · iOS · DESKTOP', start: 'Start a project', call: 'Call our studio', team: 'ONE CREATIVE TEAM.<br>FROM CONCEPT TO COMPLETION.', scroll: 'SCROLL TO EXPLORE ↓', live: 'LIVE PRODUCT PREVIEW', rotate: 'DRAG TO ROTATE', stamp: 'DESIGNED TO<br>SHOW UP.', picker: 'EXPLORE ALL SERVICES IN 3D', loading: 'BUILDING YOUR PREVIEW' },
    ticker: ['GOOD IDEAS DESERVE TO GO BIG', 'DESIGN THAT GETS NOTICED', 'PRINT MADE TO LAST', 'GOOD IDEAS DESERVE TO GO BIG', 'DESIGN THAT GETS NOTICED', 'PRINT MADE TO LAST'],
    services: { eyebrow: '02 / OUR SERVICES', eyebrowEnd: '16 SERVICES · 4 CATEGORIES', title: 'Big ideas.<br><span class="muted-heading">Made tangible.</span>', intro: 'From street-level statements to the details inside your office, every piece is made to work hard in the real world.', cards: ['Large-scale<br>outdoor advertising', 'Commercial &<br>premium signage', 'Corporate &<br>educational stationery', 'Marketing &<br>promotional material'], items: [['Hoardings', 'Blacklight boards', 'Auto rickshaw advertisements'], ['Flex and vinyl printing', 'Flute boards', 'One-way vision stickering', 'Digital wall stickers'], ['School and business ID cards', 'Office files', 'School book labels'], ['Multi-color offset printing', 'Brochures and pamphlets', 'Calendars, keychains, bill books']], note: 'NEED SOMETHING ELSE?', noteLink: 'TELL US WHAT YOU’RE THINKING' },
    process: { eyebrow: '03 / NO LOOSE ENDS', title: 'One team.<br><em>Every step.</em>', intro: 'Clear communication, thoughtful craft, and a finished result you can stand behind.', steps: [['Design it<br>in 3D.', 'See the idea take shape before a single sheet is printed.', 'YOUR VISION, VISUALISED'], ['Print it<br>beautifully.', 'Premium materials, vivid colour, and a finish built to last.', 'CRAFT YOU CAN FEEL'], ['Install it<br>with care.', 'Our crew handles the on-site details, right through to the final check.', 'READY FOR THE REAL WORLD']] },
    gallery: { eyebrow: '04 / PROJECT GALLERY', eyebrowEnd: 'VISUAL INSPIRATION', title: 'Print made<br><span class="muted-heading">visible.</span>', cta: 'MAKE SOMETHING WITH US', captions: ['Hoarding / Billboard', 'Outdoor Campaign', 'Street Hoarding', 'Vinyl Banner', 'Large Format Print', 'Flex Banner', 'Business ID & Lanyard', 'School ID Cards', 'ID Card Layouts', 'Business ID Set', 'Folded Brochure', 'Promotional Print', 'Custom Keychain', 'Brochures & Catalogues', 'Offset Printing'], note: 'These are supplied reference images, not a claim that they are completed Right Ads projects. Replace them with your own photos in the assets folder.' },
    form: { eyebrow: '05 / YOUR MOVE', eyebrowEnd: 'LET’S GET IT MADE', title: 'What are we<br><em>making?</em>', intro: 'Tell us the basics. We’ll turn it into a clear brief you can send straight to our studio.', callout: 'NO BRIEF TOO BIG OR TOO EARLY.', call: 'PREFER A CALL?', top: 'PROJECT STARTER', helper: 'FILL IN WHAT YOU KNOW ✳', labels: ['Your name', 'What do you need?', 'Quantity', 'When do you need it?', 'Anything else?'], servicePrompt: 'Pick a service', optional: 'OPTIONAL', namePlaceholder: 'How should we address you?', quantityPlaceholder: 'e.g. 250', timelinePlaceholder: 'Choose a timeline', timeline: ['As soon as possible', 'Within 2 weeks', 'Within a month', 'I’m planning ahead'], notesPlaceholder: 'Size, location, a rough idea — it all helps.', submit: 'Build my WhatsApp brief', copy: 'Copy brief', privacy: 'YOUR DETAILS ARE ONLY USED TO RESPOND TO THIS ENQUIRY.', sent: 'Your WhatsApp brief is ready in a new tab.', copied: 'Brief copied. Paste it into an email or message.' },
    closing: { eyebrow: 'YOUR IDEA, OUT IN THE WORLD', note: 'Let’s make something people remember.' }, footer: { tagline: 'MADE HERE.<br>MEANT TO BE SEEN.', contact: 'LET’S MAKE A GOOD IMPRESSION.', call: 'CALL THE STUDIO', whatsapp: 'WHATSAPP US', social: 'SOCIAL PROFILES / ADD LINKS IN CONFIG', bottom: 'GOOD WORK. DONE PROPERLY.', back: 'BACK TO TOP' },
    voice: { kicker: 'RIGHT ADS · GUIDE', title: 'Need a hand?', description: 'Listen to a quick guide or ask for a section in English, Hindi or Telugu.', instructions: 'Tap “Start listening”, allow microphone access, then say one command. Voice input varies by browser; the buttons below always work.', examples: 'Try: “Show services” · “Show 3D keychains” · “Open gallery” · “WhatsApp”', toggle: 'Voice help', speak: 'Speak guide', listen: 'Start listening', stop: 'Stop voice', close: 'Close voice help', statusReady: 'Choose an action below or start listening.', statusSpeaking: 'Speaking the guide…', statusListening: 'Listening once… say one command clearly.', statusUnsupported: 'This browser cannot take voice commands. Use the action buttons below; the spoken guide may still work.', statusHeard: 'Heard: ', statusNoMatch: 'I didn’t match that command. Try one of the examples above.', statusError: 'Microphone unavailable. Check browser permission, connection, and try again.', statusNoSpeech: 'I didn’t hear speech. Tap Start listening and speak after the prompt.', statusPermission: 'Allow microphone access in your browser, then try again.', statusNetwork: 'Voice recognition needs a working connection on this browser.', statusLanguageUnsupported: 'This browser speech recognizer does not support this language. Try an updated browser with that language enabled, or use the buttons below.', statusSpeechUnsupported: 'Your browser cannot speak this guide. You can still read the instructions and use the buttons below.', statusVoiceUnavailable: 'This device has no installed voice for this language. Add a Hindi or Telugu voice in your device speech settings, then reload this page.', statusMicrophone: 'No microphone was found. Use the buttons below.', reference: 'SUPPLIED EXAMPLE PHOTO', showServices: 'Services', show3d: '3D preview', showGallery: 'Gallery', showWhatsApp: 'WhatsApp', guide: 'Welcome to Right Ads. Choose English, Hindi, or Telugu at the top. To use voice, tap Start Listening, allow microphone access, and say one command: services, three-D keychains, gallery, call, or WhatsApp. Voice input depends on your browser, so the buttons also work without it. Explore all sixteen services in the 3D viewer or use the inquiry form for a quote.', services: 'Services', work: 'Gallery', call: 'Call' },
    whatsapp: { intro: 'Hi Right Ads, I’d like a quote for a print project.', name: 'Name', service: 'Service', quantity: 'Quantity', timeline: 'Timeline', details: 'Project details', missing: 'Not provided', generic: 'Design, printing and installation' }
  },
  hi: {
    lang: 'hi', pageTitle: 'राइट ऐड्स — अपने ब्रांड को सबसे अलग दिखाएँ',
    announcement: ['डिज़ाइन · प्रिंट · इंस्टॉल', 'हर नज़र आप पर'],
    nav: ['हमारी सेवाएँ', 'काम करने का तरीका', 'तस्वीरें'], headerCall: 'हमसे बात करें', menu: 'मेन्यू खोलें',
    hero: { eyebrow: '01 / पूरी प्रिंट सेवा', eyebrowEnd: 'असर के लिए तैयार', title: 'आपकी सोच।<br><span class="headline-accent">दुनिया के सामने।</span>', lede: 'पहले स्केच से लेकर आख़िरी इंस्टॉलेशन तक, हम आपके ब्रांड को सबकी नज़र में लाते हैं।', compat: 'मोबाइल · ANDROID · iOS · डेस्कटॉप पर काम करता है', start: 'प्रोजेक्ट शुरू करें', call: 'स्टूडियो को कॉल करें', team: 'एक क्रिएटिव टीम।<br>सोच से पूरा होने तक।', scroll: 'आगे देखने के लिए स्क्रॉल करें ↓', live: 'लाइव 3D प्रीव्यू', rotate: 'घुमाने के लिए खींचें', stamp: 'ऐसा डिज़ाइन<br>जो दिखे।', picker: 'सभी सेवाएँ 3D में देखें', loading: 'प्रीव्यू तैयार हो रहा है' },
    ticker: ['अच्छे आइडिया बड़े दिखने चाहिए', 'डिज़ाइन जो नज़र आए', 'टिकाऊ प्रिंट', 'अच्छे आइडिया बड़े दिखने चाहिए', 'डिज़ाइन जो नज़र आए', 'टिकाऊ प्रिंट'],
    services: { eyebrow: '02 / हमारी सेवाएँ', eyebrowEnd: '16 सेवाएँ · 4 श्रेणियाँ', title: 'बड़े आइडिया।<br><span class="muted-heading">अब हक़ीक़त में।</span>', intro: 'सड़क पर दिखने वाले विज्ञापन से लेकर आपके ऑफिस की स्टेशनरी तक—हर चीज़ असली इस्तेमाल के लिए तैयार।', cards: ['बड़े पैमाने के<br>आउटडोर विज्ञापन', 'कमर्शियल और<br>प्रीमियम साइनेज', 'कॉर्पोरेट और<br>शैक्षिक स्टेशनरी', 'मार्केटिंग और<br>प्रचार सामग्री'], items: [['होर्डिंग', 'ब्लैकलाइट बोर्ड', 'ऑटो रिक्शा विज्ञापन'], ['फ्लेक्स और विनाइल प्रिंटिंग', 'फ्लूट बोर्ड', 'वन-वे विज़न स्टिकरिंग', 'डिजिटल वॉल स्टिकर'], ['स्कूल और बिज़नेस ID कार्ड', 'ऑफिस फाइलें', 'स्कूल बुक लेबल'], ['मल्टी-कलर ऑफ़सेट प्रिंटिंग', 'ब्रोशर और पैम्फलेट', 'कैलेंडर, कीचेन, बिल बुक']], note: 'कुछ अलग चाहिए?', noteLink: 'अपना आइडिया हमें बताएँ' },
    process: { eyebrow: '03 / शुरू से अंत तक', title: 'एक टीम।<br><em>हर क़दम पर।</em>', intro: 'साफ़ बातचीत, सोच-समझकर किया काम और ऐसा नतीजा जिस पर आप भरोसा करें।', steps: [['3D में<br>डिज़ाइन करें।', 'प्रिंट शुरू होने से पहले अपना आइडिया आकार लेते देखें।', 'आपकी सोच, पहले से सामने'], ['बेहतरीन<br>प्रिंट करें।', 'प्रीमियम मटेरियल, चमकदार रंग और टिकाऊ फिनिश।', 'क्वालिटी जिसे महसूस करें'], ['ध्यान से<br>इंस्टॉल करें।', 'हमारी टीम साइट पर हर छोटी बात संभालती है—आख़िरी जाँच तक।', 'असली दुनिया के लिए तैयार']] },
    gallery: { eyebrow: '04 / प्रोजेक्ट गैलरी', eyebrowEnd: 'डिज़ाइन की प्रेरणा', title: 'प्रिंट जो<br><span class="muted-heading">दिखाई दे।</span>', cta: 'हमारे साथ कुछ बनाएँ', captions: ['होर्डिंग / बिलबोर्ड', 'आउटडोर कैंपेन', 'स्ट्रीट होर्डिंग', 'विनाइल बैनर', 'बड़े आकार का प्रिंट', 'फ्लेक्स बैनर', 'बिज़नेस ID और लेनयार्ड', 'स्कूल ID कार्ड', 'ID कार्ड डिज़ाइन', 'बिज़नेस ID सेट', 'फोल्डेड ब्रोशर', 'प्रमोशनल प्रिंट', 'कस्टम कीचेन', 'ब्रोशर और कैटलॉग', 'ऑफ़सेट प्रिंटिंग'], note: 'ये दिए गए संदर्भ चित्र हैं; इन्हें Right Ads के पूरे किए गए काम के रूप में नहीं दिखाया गया है। अपने काम की तस्वीरें assets फ़ोल्डर में जोड़ें।' },
    form: { eyebrow: '05 / अब आपकी बारी', eyebrowEnd: 'काम शुरू करें', title: 'क्या बनाना<br><em>है?</em>', intro: 'ज़रूरी बातें बताएँ। हम इसे एक साफ़ ब्रीफ़ में बदलकर सीधे स्टूडियो को भेजेंगे।', callout: 'हर आइडिया सुनने के लिए तैयार हैं।', call: 'कॉल करना पसंद करेंगे?', top: 'प्रोजेक्ट शुरू करें', helper: 'जितना पता है, भरें ✳', labels: ['आपका नाम', 'क्या चाहिए?', 'मात्रा', 'कब तक चाहिए?', 'कुछ और जानकारी?'], servicePrompt: 'सेवा चुनें', optional: 'वैकल्पिक', namePlaceholder: 'आपको किस नाम से बुलाएँ?', quantityPlaceholder: 'जैसे 250', timelinePlaceholder: 'समय चुनें', timeline: ['जितनी जल्दी हो सके', '2 हफ़्तों के अंदर', 'एक महीने के अंदर', 'आगे की योजना'], notesPlaceholder: 'साइज़, जगह या कोई शुरुआती आइडिया लिखें।', submit: 'WhatsApp ब्रीफ़ बनाएँ', copy: 'ब्रीफ़ कॉपी करें', privacy: 'आपकी जानकारी का उपयोग केवल इस पूछताछ का जवाब देने के लिए होगा।', sent: 'आपका WhatsApp ब्रीफ़ नए टैब में तैयार है।', copied: 'ब्रीफ़ कॉपी हो गया। इसे ईमेल या मैसेज में पेस्ट करें।' },
    closing: { eyebrow: 'आपका विचार, दुनिया के सामने', note: 'आइए, कुछ ऐसा बनाएँ जिसे लोग याद रखें।' }, footer: { tagline: 'यहीं बना।<br>सबको दिखे।', contact: 'अच्छा प्रभाव बनाएँ।', call: 'स्टूडियो को कॉल करें', whatsapp: 'WhatsApp करें', social: 'सोशल लिंक / कॉन्फ़िग में जोड़ें', bottom: 'बेहतरीन काम। सही तरीके से।', back: 'ऊपर जाएँ' },
    voice: { kicker: 'राइट ऐड्स · सहायता', title: 'मदद चाहिए?', description: 'हिंदी, तेलुगु या अंग्रेज़ी में गाइड सुनें या वेबसाइट का कोई भाग खोलने को कहें।', instructions: '“सुनना शुरू करें” दबाएँ, माइक्रोफ़ोन की अनुमति दें और एक कमांड बोलें। आवाज़ पहचान हर ब्राउज़र में नहीं चलती; नीचे के बटन हमेशा काम करेंगे।', examples: 'कहें: “सेवाएँ दिखाएँ” · “कीचेन का 3D दिखाएँ” · “गैलरी खोलें” · “WhatsApp खोलें”', toggle: 'आवाज़ से मदद', speak: 'गाइड सुनें', listen: 'सुनना शुरू करें', stop: 'आवाज़ रोकें', close: 'सहायता बंद करें', statusReady: 'नीचे कोई विकल्प चुनें या सुनना शुरू करें।', statusSpeaking: 'गाइड सुनाई जा रही है…', statusListening: 'एक बार सुन रहे हैं… एक कमांड साफ़ बोलें।', statusUnsupported: 'यह ब्राउज़र वॉइस कमांड नहीं ले सकता। नीचे के बटन इस्तेमाल करें; गाइड फिर भी सुन सकते हैं।', statusHeard: 'सुना: ', statusNoMatch: 'कमांड समझ नहीं आया। ऊपर दिए उदाहरणों में से एक बोलें।', statusError: 'माइक्रोफ़ोन उपलब्ध नहीं है। ब्राउज़र अनुमति और कनेक्शन जाँचें।', statusNoSpeech: 'आवाज़ नहीं सुनाई दी। सुनना शुरू करें दबाकर बोलें।', statusPermission: 'ब्राउज़र में माइक्रोफ़ोन की अनुमति दें, फिर दोबारा कोशिश करें।', statusNetwork: 'इस ब्राउज़र में आवाज़ पहचानने के लिए इंटरनेट कनेक्शन चाहिए।', statusLanguageUnsupported: 'यह ब्राउज़र इस भाषा में आवाज़ नहीं पहचान सकता। अपडेट किए हुए ब्राउज़र में भाषा चालू करें या नीचे के बटन इस्तेमाल करें।', statusSpeechUnsupported: 'आपका ब्राउज़र यह गाइड बोल नहीं सकता। निर्देश पढ़ें और नीचे दिए बटन इस्तेमाल करें।', statusVoiceUnavailable: 'इस डिवाइस में इस भाषा की आवाज़ इंस्टॉल नहीं है। डिवाइस की स्पीच सेटिंग में हिंदी या तेलुगु आवाज़ जोड़कर पेज फिर खोलें।', statusMicrophone: 'माइक्रोफ़ोन नहीं मिला। नीचे के बटन इस्तेमाल करें।', reference: 'दिया गया नमूना चित्र', showServices: 'सेवाएँ', show3d: '3D प्रीव्यू', showGallery: 'गैलरी', showWhatsApp: 'WhatsApp', guide: 'राइट ऐड्स में आपका स्वागत है। अंग्रेज़ी, हिंदी या तेलुगु चुनें। आवाज़ से चलाने के लिए सुनना शुरू करें दबाएँ, माइक्रोफ़ोन की अनुमति दें और एक कमांड कहें: सेवाएँ, 3D कीचेन, गैलरी, कॉल या WhatsApp। हर ब्राउज़र आवाज़ नहीं पहचानता, इसलिए नीचे के बटन भी इस्तेमाल कर सकते हैं। 3D व्यू में सभी सोलह सेवाएँ देखें या पूछताछ फ़ॉर्म से कीमत पूछें।', services: 'सेवाएँ', work: 'गैलरी', call: 'कॉल' },
    whatsapp: { intro: 'नमस्ते राइट ऐड्स, मुझे प्रिंट प्रोजेक्ट का कोट चाहिए।', name: 'नाम', service: 'सेवा', quantity: 'मात्रा', timeline: 'समय', details: 'प्रोजेक्ट जानकारी', missing: 'नहीं दिया', generic: 'डिज़ाइन, प्रिंटिंग और इंस्टॉलेशन' }
  },
  te: {
    lang: 'te', pageTitle: 'రైట్ యాడ్స్ — మీ బ్రాండ్ అందరికీ కనిపించేలా',
    announcement: ['డిజైన్ · ప్రింట్ · ఇన్‌స్టాల్', 'అందరి దృష్టిలో'],
    nav: ['మా సేవలు', 'మా పని విధానం', 'చిత్రాలు'], headerCall: 'మాతో మాట్లాడండి', menu: 'మెనూను తెరవండి',
    hero: { eyebrow: '01 / పూర్తి ప్రింట్ సేవలు', eyebrowEnd: 'ప్రభావం కోసం సిద్ధం', title: 'మీ ఆలోచన.<br><span class="headline-accent">ప్రపంచం ముందుకు.</span>', lede: 'మొదటి స్కెచ్ నుంచి చివరి ఇన్‌స్టాలేషన్ వరకు, మీ బ్రాండ్ అందరికీ కనిపించేలా చేస్తాం.', compat: 'మొబైల్ · ANDROID · iOS · డెస్క్‌టాప్‌లో పనిచేస్తుంది', start: 'ప్రాజెక్ట్ ప్రారంభించండి', call: 'స్టూడియోకు కాల్ చేయండి', team: 'ఒకే క్రియేటివ్ బృందం.<br>ఆలోచన నుంచి పూర్తి వరకు.', scroll: 'మరింత చూడండి ↓', live: 'లైవ్ 3D ప్రివ్యూ', rotate: 'తిప్పడానికి లాగండి', stamp: 'కనిపించేలా<br>రూపొందించాం.', picker: 'అన్ని సేవలను 3Dలో చూడండి', loading: 'ప్రివ్యూ సిద్ధమవుతోంది' },
    ticker: ['మంచి ఆలోచనలకు పెద్ద రూపం ఇవ్వాలి', 'కనిపించే డిజైన్', 'ఎక్కువకాలం నిలిచే ప్రింట్', 'మంచి ఆలోచనలకు పెద్ద రూపం ఇవ్వాలి', 'కనిపించే డిజైన్', 'ఎక్కువకాలం నిలిచే ప్రింట్'],
    services: { eyebrow: '02 / మా సేవలు', eyebrowEnd: '16 సేవలు · 4 విభాగాలు', title: 'పెద్ద ఆలోచనలు.<br><span class="muted-heading">ఇప్పుడు నిజ రూపంలో.</span>', intro: 'వీధి ప్రకటనల నుంచి మీ ఆఫీస్‌లోని వివరాల వరకు—ప్రతి పనినీ వాస్తవ వినియోగానికి సిద్ధం చేస్తాం.', cards: ['భారీ స్థాయి<br>అవుట్‌డోర్ ప్రకటనలు', 'కమర్షియల్ &<br>ప్రీమియం సైన్‌బోర్డులు', 'కార్పొరేట్ &<br>విద్యా స్టేషనరీ', 'మార్కెటింగ్ &<br>ప్రమోషనల్ మెటీరియల్'], items: [['హోర్డింగ్‌లు', 'బ్లాక్‌లైట్ బోర్డులు', 'ఆటో రిక్షా ప్రకటనలు'], ['ఫ్లెక్స్ & వినైల్ ప్రింటింగ్', 'ఫ్లూట్ బోర్డులు', 'వన్-వే విజన్ స్టికరింగ్', 'డిజిటల్ వాల్ స్టిక్కర్లు'], ['స్కూల్ & బిజినెస్ ID కార్డులు', 'ఆఫీస్ ఫైళ్లు', 'స్కూల్ బుక్ లేబుళ్లు'], ['మల్టీ-కలర్ ఆఫ్‌సెట్ ప్రింటింగ్', 'బ్రోచర్లు & పాంప్లెట్లు', 'క్యాలెండర్లు, కీచెయిన్‌లు, బిల్ బుక్స్']], note: 'మరేదైనా కావాలా?', noteLink: 'మీ ఆలోచనను మాతో పంచుకోండి' },
    process: { eyebrow: '03 / మొదటి నుంచి చివరి వరకు', title: 'ఒకే బృందం.<br><em>ప్రతి దశలో.</em>', intro: 'స్పష్టమైన మాట, శ్రద్ధతో కూడిన పని, మీరు నమ్మగలిగే ఫలితం.', steps: [['3Dలో<br>డిజైన్.', 'ప్రింట్ మొదలుకాకముందే మీ ఆలోచన రూపం దాల్చడం చూడండి.', 'మీ ఆలోచనకు స్పష్టమైన రూపం'], ['అద్భుతంగా<br>ప్రింట్.', 'ప్రీమియం మెటీరియల్స్, ప్రకాశవంతమైన రంగులు, మన్నికైన ఫినిష్.', 'నాణ్యతను అనుభవించండి'], ['జాగ్రత్తగా<br>ఇన్‌స్టాల్.', 'చివరి తనిఖీ వరకు మా బృందం స్థలంలో ప్రతి వివరాన్ని చూసుకుంటుంది.', 'వాస్తవ వినియోగానికి సిద్ధం']] },
    gallery: { eyebrow: '04 / ప్రాజెక్ట్ గ్యాలరీ', eyebrowEnd: 'డిజైన్ స్ఫూర్తి', title: 'ప్రింట్‌కు<br><span class="muted-heading">కనిపించే రూపం.</span>', cta: 'మనమూ ఏదైనా సృష్టిద్దాం', captions: ['హోర్డింగ్ / బిల్‌బోర్డ్', 'అవుట్‌డోర్ క్యాంపెయిన్', 'వీధి హోర్డింగ్', 'వినైల్ బ్యానర్', 'లార్జ్ ఫార్మాట్ ప్రింట్', 'ఫ్లెక్స్ బ్యానర్', 'బిజినెస్ ID & లాన్యార్డ్', 'స్కూల్ ID కార్డులు', 'ID కార్డ్ లేఅవుట్లు', 'బిజినెస్ ID సెట్', 'ఫోల్డెడ్ బ్రోచర్', 'ప్రమోషనల్ ప్రింట్', 'కస్టమ్ కీచెయిన్', 'బ్రోచర్లు & కేటలాగ్‌లు', 'ఆఫ్‌సెట్ ప్రింటింగ్'], note: 'ఇవి మీరు అందించిన సూచన చిత్రాలు మాత్రమే; ఇవి రైట్ యాడ్స్ పూర్తి చేసిన పనులని సూచించవు. మీ ప్రాజెక్ట్ ఫోటోలను assets ఫోల్డర్‌లో చేర్చండి.' },
    form: { eyebrow: '05 / మీ వంతు', eyebrowEnd: 'పని మొదలుపెడదాం', title: 'ఏమి<br><em>తయారు చేద్దాం?</em>', intro: 'ప్రాథమిక వివరాలు చెప్పండి. వాటిని మా స్టూడియోకు పంపగల స్పష్టమైన బ్రీఫ్‌గా తయారు చేస్తాం.', callout: 'మీ ఆలోచన ఏదైనా చెప్పండి.', call: 'కాల్ చేయాలనుకుంటున్నారా?', top: 'ప్రాజెక్ట్ వివరాలు', helper: 'తెలిసినవి నమోదు చేయండి ✳', labels: ['మీ పేరు', 'ఏం కావాలి?', 'పరిమాణం', 'ఎప్పటికి కావాలి?', 'ఇంకేమైనా వివరాలు?'], servicePrompt: 'సేవను ఎంచుకోండి', optional: 'ఐచ్ఛికం', namePlaceholder: 'మిమ్మల్ని ఏ పేరుతో పిలవాలి?', quantityPlaceholder: 'ఉదా. 250', timelinePlaceholder: 'సమయం ఎంచుకోండి', timeline: ['వీలైనంత త్వరగా', '2 వారాల్లోపు', 'ఒక నెలలోపు', 'ముందస్తు ప్రణాళిక'], notesPlaceholder: 'పరిమాణం, ప్రదేశం లేదా మీ ప్రాథమిక ఆలోచన రాయండి.', submit: 'WhatsApp బ్రీఫ్ తయారు చేయండి', copy: 'బ్రీఫ్ కాపీ చేయండి', privacy: 'మీ వివరాలు ఈ విచారణకు సమాధానం ఇవ్వడానికి మాత్రమే ఉపయోగిస్తాం.', sent: 'మీ WhatsApp బ్రీఫ్ కొత్త ట్యాబ్‌లో సిద్ధంగా ఉంది.', copied: 'బ్రీఫ్ కాపీ అయింది. ఇమెయిల్ లేదా మెసేజ్‌లో పేస్ట్ చేయండి.' },
    closing: { eyebrow: 'మీ ఆలోచన, ప్రపంచం ముందుకు', note: 'గుర్తుండిపోయేలా ఏదైనా సృష్టిద్దాం.' }, footer: { tagline: 'ఇక్కడే తయారు.<br>అందరికీ కనిపించేలా.', contact: 'మంచి ముద్ర వేయండి.', call: 'స్టూడియోకు కాల్', whatsapp: 'WhatsApp చేయండి', social: 'సోషల్ లింకులు / కాన్ఫిగ్‌లో జోడించండి', bottom: 'నాణ్యమైన పని. సరైన విధంగా.', back: 'పైకి వెళ్లండి' },
    voice: { kicker: 'రైట్ యాడ్స్ · సహాయం', title: 'సహాయం కావాలా?', description: 'తెలుగు, హిందీ లేదా ఇంగ్లీష్‌లో గైడ్ వినండి లేదా వెబ్‌సైట్ భాగాన్ని తెరవమని చెప్పండి.', instructions: '“వినడం ప్రారంభించండి” నొక్కండి, మైక్రోఫోన్ అనుమతించండి, ఒక కమాండ్ చెప్పండి. ప్రతి బ్రౌజర్‌లో వాయిస్ గుర్తింపు ఉండదు; దిగువ బటన్లు ఎప్పుడూ పనిచేస్తాయి.', examples: 'ఇలా చెప్పండి: “సేవలు చూపించు” · “కీచెయిన్ 3D చూపించు” · “గ్యాలరీ తెరువు” · “WhatsApp తెరువు”', toggle: 'వాయిస్ సహాయం', speak: 'గైడ్ వినండి', listen: 'వినడం ప్రారంభించండి', stop: 'ఆపండి', close: 'వాయిస్ సహాయం మూసివేయండి', statusReady: 'దిగువ ఎంపికను నొక్కండి లేదా వినడం ప్రారంభించండి.', statusSpeaking: 'గైడ్ వినిపిస్తోంది…', statusListening: 'ఒక్కసారి వింటున్నాం… ఒక కమాండ్ స్పష్టంగా చెప్పండి.', statusUnsupported: 'ఈ బ్రౌజర్ వాయిస్ కమాండ్లు స్వీకరించదు. దిగువ బటన్లు ఉపయోగించండి; గైడ్ వినిపించవచ్చు.', statusHeard: 'విన్నది: ', statusNoMatch: 'కమాండ్ అర్థం కాలేదు. పై ఉదాహరణల్లో ఒకటి చెప్పండి.', statusError: 'మైక్రోఫోన్ అందుబాటులో లేదు. అనుమతి, కనెక్షన్ తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.', statusNoSpeech: 'మాట వినిపించలేదు. వినడం ప్రారంభించండి నొక్కి మాట్లాడండి.', statusPermission: 'బ్రౌజర్‌లో మైక్రోఫోన్ అనుమతించండి, ఆపై మళ్లీ ప్రయత్నించండి.', statusNetwork: 'ఈ బ్రౌజర్‌లో వాయిస్ గుర్తింపుకు ఇంటర్నెట్ కనెక్షన్ అవసరం.', statusLanguageUnsupported: 'ఈ బ్రౌజర్ ఈ భాషలో వాయిస్ గుర్తించదు. అప్‌డేట్ చేసిన బ్రౌజర్‌లో ఈ భాషను ప్రారంభించండి లేదా దిగువ బటన్లు వాడండి.', statusSpeechUnsupported: 'మీ బ్రౌజర్ ఈ గైడ్‌ను మాట్లాడలేకపోతోంది. సూచనలు చదివి, దిగువ బటన్లు ఉపయోగించండి.', statusVoiceUnavailable: 'ఈ పరికరంలో ఈ భాష వాయిస్ ఇన్‌స్టాల్ కాలేదు. పరికరం స్పీచ్ సెట్టింగ్స్‌లో హిందీ లేదా తెలుగు వాయిస్ జోడించి పేజీ మళ్లీ తెరవండి.', statusMicrophone: 'మైక్రోఫోన్ కనిపించలేదు. దిగువ బటన్లు ఉపయోగించండి.', reference: 'మీరు ఇచ్చిన నమూనా చిత్రం', showServices: 'సేవలు', show3d: '3D ప్రివ్యూ', showGallery: 'గ్యాలరీ', showWhatsApp: 'WhatsApp', guide: 'రైట్ యాడ్స్‌కు స్వాగతం. ఇంగ్లీష్, హిందీ లేదా తెలుగు ఎంచుకోండి. వాయిస్ ఉపయోగించడానికి వినడం ప్రారంభించండి నొక్కి, మైక్రోఫోన్ అనుమతించి, ఒక కమాండ్ చెప్పండి: సేవలు, 3D కీచెయిన్, గ్యాలరీ, కాల్ లేదా WhatsApp. ప్రతి బ్రౌజర్ వాయిస్ గుర్తించదు, కాబట్టి దిగువ బటన్లు కూడా ఉపయోగించండి. 3D వ్యూలో పదహారు సేవలు చూడండి లేదా విచారణ ఫారమ్‌తో ధర అడగండి.', services: 'సేవలు', work: 'గ్యాలరీ', call: 'కాల్' },
    whatsapp: { intro: 'నమస్కారం రైట్ యాడ్స్, ప్రింట్ ప్రాజెక్ట్ కోసం ధర కావాలి.', name: 'పేరు', service: 'సేవ', quantity: 'పరిమాణం', timeline: 'సమయం', details: 'ప్రాజెక్ట్ వివరాలు', missing: 'తెలియజేయలేదు', generic: 'డిజైన్, ప్రింటింగ్ & ఇన్‌స్టాలేషన్' }
  }
};

